package com.wjp.fem.dao;

import com.wjp.fem.bean.Electricity;
import com.wjp.fem.bean.ElectricityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ElectricityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    long countByExample(ElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByExample(ElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String elecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insert(Electricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insertSelective(Electricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    List<Electricity> selectByExample(ElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    Electricity selectByPrimaryKey(String elecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Electricity record, @Param("example") ElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Electricity record, @Param("example") ElectricityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Electricity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(Electricity record);
}