package com.wjp.fem.dao;

import com.wjp.fem.bean.ForeUserSpot;
import com.wjp.fem.bean.ForeUserSpotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForeUserSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    long countByExample(ForeUserSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByExample(ForeUserSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insert(ForeUserSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insertSelective(ForeUserSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    List<ForeUserSpot> selectByExample(ForeUserSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    ForeUserSpot selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ForeUserSpot record, @Param("example") ForeUserSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ForeUserSpot record, @Param("example") ForeUserSpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ForeUserSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(ForeUserSpot record);
}