package com.wjp.fem.dao;

import com.wjp.fem.bean.RecordTemp;
import com.wjp.fem.bean.RecordTempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    long countByExample(RecordTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByExample(RecordTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long recordTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insert(RecordTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insertSelective(RecordTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    List<RecordTemp> selectByExample(RecordTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    RecordTemp selectByPrimaryKey(Long recordTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") RecordTemp record, @Param("example") RecordTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExample(@Param("record") RecordTemp record, @Param("example") RecordTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(RecordTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(RecordTemp record);
}