package com.wjp.fem.dao;

import com.wjp.fem.bean.Spot;
import com.wjp.fem.bean.SpotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    long countByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer spotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insert(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insertSelective(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    List<Spot> selectByExample(SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    Spot selectByPrimaryKey(Integer spotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Spot record, @Param("example") SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Spot record, @Param("example") SpotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Spot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(Spot record);
}