package com.wjp.fem.dao;

import com.wjp.fem.bean.Temperature;
import com.wjp.fem.bean.TemperatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemperatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    long countByExample(TemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByExample(TemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int deleteByPrimaryKey(String tempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insert(Temperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int insertSelective(Temperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    List<Temperature> selectByExample(TemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    Temperature selectByPrimaryKey(String tempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") Temperature record, @Param("example") TemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByExample(@Param("record") Temperature record, @Param("example") TemperatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(Temperature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    int updateByPrimaryKey(Temperature record);
}