package com.wjp.fem.bean;

import java.util.ArrayList;
import java.util.List;

public class ElectricityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public ElectricityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andElecIdIsNull() {
            addCriterion("elec_id is null");
            return (Criteria) this;
        }

        public Criteria andElecIdIsNotNull() {
            addCriterion("elec_id is not null");
            return (Criteria) this;
        }

        public Criteria andElecIdEqualTo(String value) {
            addCriterion("elec_id =", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdNotEqualTo(String value) {
            addCriterion("elec_id <>", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdGreaterThan(String value) {
            addCriterion("elec_id >", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdGreaterThanOrEqualTo(String value) {
            addCriterion("elec_id >=", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdLessThan(String value) {
            addCriterion("elec_id <", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdLessThanOrEqualTo(String value) {
            addCriterion("elec_id <=", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdLike(String value) {
            addCriterion("elec_id like", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdNotLike(String value) {
            addCriterion("elec_id not like", value, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdIn(List<String> values) {
            addCriterion("elec_id in", values, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdNotIn(List<String> values) {
            addCriterion("elec_id not in", values, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdBetween(String value1, String value2) {
            addCriterion("elec_id between", value1, value2, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecIdNotBetween(String value1, String value2) {
            addCriterion("elec_id not between", value1, value2, "elecId");
            return (Criteria) this;
        }

        public Criteria andElecNameIsNull() {
            addCriterion("elec_name is null");
            return (Criteria) this;
        }

        public Criteria andElecNameIsNotNull() {
            addCriterion("elec_name is not null");
            return (Criteria) this;
        }

        public Criteria andElecNameEqualTo(String value) {
            addCriterion("elec_name =", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameNotEqualTo(String value) {
            addCriterion("elec_name <>", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameGreaterThan(String value) {
            addCriterion("elec_name >", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameGreaterThanOrEqualTo(String value) {
            addCriterion("elec_name >=", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameLessThan(String value) {
            addCriterion("elec_name <", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameLessThanOrEqualTo(String value) {
            addCriterion("elec_name <=", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameLike(String value) {
            addCriterion("elec_name like", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameNotLike(String value) {
            addCriterion("elec_name not like", value, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameIn(List<String> values) {
            addCriterion("elec_name in", values, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameNotIn(List<String> values) {
            addCriterion("elec_name not in", values, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameBetween(String value1, String value2) {
            addCriterion("elec_name between", value1, value2, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecNameNotBetween(String value1, String value2) {
            addCriterion("elec_name not between", value1, value2, "elecName");
            return (Criteria) this;
        }

        public Criteria andElecValueIsNull() {
            addCriterion("elec_value is null");
            return (Criteria) this;
        }

        public Criteria andElecValueIsNotNull() {
            addCriterion("elec_value is not null");
            return (Criteria) this;
        }

        public Criteria andElecValueEqualTo(Integer value) {
            addCriterion("elec_value =", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueNotEqualTo(Integer value) {
            addCriterion("elec_value <>", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueGreaterThan(Integer value) {
            addCriterion("elec_value >", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("elec_value >=", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueLessThan(Integer value) {
            addCriterion("elec_value <", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueLessThanOrEqualTo(Integer value) {
            addCriterion("elec_value <=", value, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueIn(List<Integer> values) {
            addCriterion("elec_value in", values, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueNotIn(List<Integer> values) {
            addCriterion("elec_value not in", values, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueBetween(Integer value1, Integer value2) {
            addCriterion("elec_value between", value1, value2, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecValueNotBetween(Integer value1, Integer value2) {
            addCriterion("elec_value not between", value1, value2, "elecValue");
            return (Criteria) this;
        }

        public Criteria andElecEarlyIsNull() {
            addCriterion("elec_early is null");
            return (Criteria) this;
        }

        public Criteria andElecEarlyIsNotNull() {
            addCriterion("elec_early is not null");
            return (Criteria) this;
        }

        public Criteria andElecEarlyEqualTo(Integer value) {
            addCriterion("elec_early =", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyNotEqualTo(Integer value) {
            addCriterion("elec_early <>", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyGreaterThan(Integer value) {
            addCriterion("elec_early >", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyGreaterThanOrEqualTo(Integer value) {
            addCriterion("elec_early >=", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyLessThan(Integer value) {
            addCriterion("elec_early <", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyLessThanOrEqualTo(Integer value) {
            addCriterion("elec_early <=", value, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyIn(List<Integer> values) {
            addCriterion("elec_early in", values, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyNotIn(List<Integer> values) {
            addCriterion("elec_early not in", values, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyBetween(Integer value1, Integer value2) {
            addCriterion("elec_early between", value1, value2, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecEarlyNotBetween(Integer value1, Integer value2) {
            addCriterion("elec_early not between", value1, value2, "elecEarly");
            return (Criteria) this;
        }

        public Criteria andElecWarningIsNull() {
            addCriterion("elec_warning is null");
            return (Criteria) this;
        }

        public Criteria andElecWarningIsNotNull() {
            addCriterion("elec_warning is not null");
            return (Criteria) this;
        }

        public Criteria andElecWarningEqualTo(Integer value) {
            addCriterion("elec_warning =", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningNotEqualTo(Integer value) {
            addCriterion("elec_warning <>", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningGreaterThan(Integer value) {
            addCriterion("elec_warning >", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningGreaterThanOrEqualTo(Integer value) {
            addCriterion("elec_warning >=", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningLessThan(Integer value) {
            addCriterion("elec_warning <", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningLessThanOrEqualTo(Integer value) {
            addCriterion("elec_warning <=", value, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningIn(List<Integer> values) {
            addCriterion("elec_warning in", values, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningNotIn(List<Integer> values) {
            addCriterion("elec_warning not in", values, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningBetween(Integer value1, Integer value2) {
            addCriterion("elec_warning between", value1, value2, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecWarningNotBetween(Integer value1, Integer value2) {
            addCriterion("elec_warning not between", value1, value2, "elecWarning");
            return (Criteria) this;
        }

        public Criteria andElecStateIsNull() {
            addCriterion("elec_state is null");
            return (Criteria) this;
        }

        public Criteria andElecStateIsNotNull() {
            addCriterion("elec_state is not null");
            return (Criteria) this;
        }

        public Criteria andElecStateEqualTo(String value) {
            addCriterion("elec_state =", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateNotEqualTo(String value) {
            addCriterion("elec_state <>", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateGreaterThan(String value) {
            addCriterion("elec_state >", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateGreaterThanOrEqualTo(String value) {
            addCriterion("elec_state >=", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateLessThan(String value) {
            addCriterion("elec_state <", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateLessThanOrEqualTo(String value) {
            addCriterion("elec_state <=", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateLike(String value) {
            addCriterion("elec_state like", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateNotLike(String value) {
            addCriterion("elec_state not like", value, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateIn(List<String> values) {
            addCriterion("elec_state in", values, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateNotIn(List<String> values) {
            addCriterion("elec_state not in", values, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateBetween(String value1, String value2) {
            addCriterion("elec_state between", value1, value2, "elecState");
            return (Criteria) this;
        }

        public Criteria andElecStateNotBetween(String value1, String value2) {
            addCriterion("elec_state not between", value1, value2, "elecState");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNull() {
            addCriterion("fore_spot_id is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNotNull() {
            addCriterion("fore_spot_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdEqualTo(Integer value) {
            addCriterion("fore_spot_id =", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotEqualTo(Integer value) {
            addCriterion("fore_spot_id <>", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThan(Integer value) {
            addCriterion("fore_spot_id >", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id >=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThan(Integer value) {
            addCriterion("fore_spot_id <", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id <=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIn(List<Integer> values) {
            addCriterion("fore_spot_id in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotIn(List<Integer> values) {
            addCriterion("fore_spot_id not in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id not between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailIsNull() {
            addCriterion("elec_spot_detail is null");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailIsNotNull() {
            addCriterion("elec_spot_detail is not null");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailEqualTo(String value) {
            addCriterion("elec_spot_detail =", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailNotEqualTo(String value) {
            addCriterion("elec_spot_detail <>", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailGreaterThan(String value) {
            addCriterion("elec_spot_detail >", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailGreaterThanOrEqualTo(String value) {
            addCriterion("elec_spot_detail >=", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailLessThan(String value) {
            addCriterion("elec_spot_detail <", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailLessThanOrEqualTo(String value) {
            addCriterion("elec_spot_detail <=", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailLike(String value) {
            addCriterion("elec_spot_detail like", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailNotLike(String value) {
            addCriterion("elec_spot_detail not like", value, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailIn(List<String> values) {
            addCriterion("elec_spot_detail in", values, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailNotIn(List<String> values) {
            addCriterion("elec_spot_detail not in", values, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailBetween(String value1, String value2) {
            addCriterion("elec_spot_detail between", value1, value2, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecSpotDetailNotBetween(String value1, String value2) {
            addCriterion("elec_spot_detail not between", value1, value2, "elecSpotDetail");
            return (Criteria) this;
        }

        public Criteria andElecStandardIsNull() {
            addCriterion("elec_standard is null");
            return (Criteria) this;
        }

        public Criteria andElecStandardIsNotNull() {
            addCriterion("elec_standard is not null");
            return (Criteria) this;
        }

        public Criteria andElecStandardEqualTo(String value) {
            addCriterion("elec_standard =", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardNotEqualTo(String value) {
            addCriterion("elec_standard <>", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardGreaterThan(String value) {
            addCriterion("elec_standard >", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardGreaterThanOrEqualTo(String value) {
            addCriterion("elec_standard >=", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardLessThan(String value) {
            addCriterion("elec_standard <", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardLessThanOrEqualTo(String value) {
            addCriterion("elec_standard <=", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardLike(String value) {
            addCriterion("elec_standard like", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardNotLike(String value) {
            addCriterion("elec_standard not like", value, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardIn(List<String> values) {
            addCriterion("elec_standard in", values, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardNotIn(List<String> values) {
            addCriterion("elec_standard not in", values, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardBetween(String value1, String value2) {
            addCriterion("elec_standard between", value1, value2, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecStandardNotBetween(String value1, String value2) {
            addCriterion("elec_standard not between", value1, value2, "elecStandard");
            return (Criteria) this;
        }

        public Criteria andElecVoltageIsNull() {
            addCriterion("elec_voltage is null");
            return (Criteria) this;
        }

        public Criteria andElecVoltageIsNotNull() {
            addCriterion("elec_voltage is not null");
            return (Criteria) this;
        }

        public Criteria andElecVoltageEqualTo(String value) {
            addCriterion("elec_voltage =", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageNotEqualTo(String value) {
            addCriterion("elec_voltage <>", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageGreaterThan(String value) {
            addCriterion("elec_voltage >", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageGreaterThanOrEqualTo(String value) {
            addCriterion("elec_voltage >=", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageLessThan(String value) {
            addCriterion("elec_voltage <", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageLessThanOrEqualTo(String value) {
            addCriterion("elec_voltage <=", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageLike(String value) {
            addCriterion("elec_voltage like", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageNotLike(String value) {
            addCriterion("elec_voltage not like", value, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageIn(List<String> values) {
            addCriterion("elec_voltage in", values, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageNotIn(List<String> values) {
            addCriterion("elec_voltage not in", values, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageBetween(String value1, String value2) {
            addCriterion("elec_voltage between", value1, value2, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecVoltageNotBetween(String value1, String value2) {
            addCriterion("elec_voltage not between", value1, value2, "elecVoltage");
            return (Criteria) this;
        }

        public Criteria andElecCurrentIsNull() {
            addCriterion("elec_current is null");
            return (Criteria) this;
        }

        public Criteria andElecCurrentIsNotNull() {
            addCriterion("elec_current is not null");
            return (Criteria) this;
        }

        public Criteria andElecCurrentEqualTo(String value) {
            addCriterion("elec_current =", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentNotEqualTo(String value) {
            addCriterion("elec_current <>", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentGreaterThan(String value) {
            addCriterion("elec_current >", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentGreaterThanOrEqualTo(String value) {
            addCriterion("elec_current >=", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentLessThan(String value) {
            addCriterion("elec_current <", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentLessThanOrEqualTo(String value) {
            addCriterion("elec_current <=", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentLike(String value) {
            addCriterion("elec_current like", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentNotLike(String value) {
            addCriterion("elec_current not like", value, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentIn(List<String> values) {
            addCriterion("elec_current in", values, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentNotIn(List<String> values) {
            addCriterion("elec_current not in", values, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentBetween(String value1, String value2) {
            addCriterion("elec_current between", value1, value2, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecCurrentNotBetween(String value1, String value2) {
            addCriterion("elec_current not between", value1, value2, "elecCurrent");
            return (Criteria) this;
        }

        public Criteria andElecTextureIsNull() {
            addCriterion("elec_texture is null");
            return (Criteria) this;
        }

        public Criteria andElecTextureIsNotNull() {
            addCriterion("elec_texture is not null");
            return (Criteria) this;
        }

        public Criteria andElecTextureEqualTo(String value) {
            addCriterion("elec_texture =", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureNotEqualTo(String value) {
            addCriterion("elec_texture <>", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureGreaterThan(String value) {
            addCriterion("elec_texture >", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureGreaterThanOrEqualTo(String value) {
            addCriterion("elec_texture >=", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureLessThan(String value) {
            addCriterion("elec_texture <", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureLessThanOrEqualTo(String value) {
            addCriterion("elec_texture <=", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureLike(String value) {
            addCriterion("elec_texture like", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureNotLike(String value) {
            addCriterion("elec_texture not like", value, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureIn(List<String> values) {
            addCriterion("elec_texture in", values, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureNotIn(List<String> values) {
            addCriterion("elec_texture not in", values, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureBetween(String value1, String value2) {
            addCriterion("elec_texture between", value1, value2, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecTextureNotBetween(String value1, String value2) {
            addCriterion("elec_texture not between", value1, value2, "elecTexture");
            return (Criteria) this;
        }

        public Criteria andElecSettingIsNull() {
            addCriterion("elec_setting is null");
            return (Criteria) this;
        }

        public Criteria andElecSettingIsNotNull() {
            addCriterion("elec_setting is not null");
            return (Criteria) this;
        }

        public Criteria andElecSettingEqualTo(String value) {
            addCriterion("elec_setting =", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingNotEqualTo(String value) {
            addCriterion("elec_setting <>", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingGreaterThan(String value) {
            addCriterion("elec_setting >", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingGreaterThanOrEqualTo(String value) {
            addCriterion("elec_setting >=", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingLessThan(String value) {
            addCriterion("elec_setting <", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingLessThanOrEqualTo(String value) {
            addCriterion("elec_setting <=", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingLike(String value) {
            addCriterion("elec_setting like", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingNotLike(String value) {
            addCriterion("elec_setting not like", value, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingIn(List<String> values) {
            addCriterion("elec_setting in", values, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingNotIn(List<String> values) {
            addCriterion("elec_setting not in", values, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingBetween(String value1, String value2) {
            addCriterion("elec_setting between", value1, value2, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSettingNotBetween(String value1, String value2) {
            addCriterion("elec_setting not between", value1, value2, "elecSetting");
            return (Criteria) this;
        }

        public Criteria andElecSizeIsNull() {
            addCriterion("elec_size is null");
            return (Criteria) this;
        }

        public Criteria andElecSizeIsNotNull() {
            addCriterion("elec_size is not null");
            return (Criteria) this;
        }

        public Criteria andElecSizeEqualTo(String value) {
            addCriterion("elec_size =", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeNotEqualTo(String value) {
            addCriterion("elec_size <>", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeGreaterThan(String value) {
            addCriterion("elec_size >", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeGreaterThanOrEqualTo(String value) {
            addCriterion("elec_size >=", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeLessThan(String value) {
            addCriterion("elec_size <", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeLessThanOrEqualTo(String value) {
            addCriterion("elec_size <=", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeLike(String value) {
            addCriterion("elec_size like", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeNotLike(String value) {
            addCriterion("elec_size not like", value, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeIn(List<String> values) {
            addCriterion("elec_size in", values, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeNotIn(List<String> values) {
            addCriterion("elec_size not in", values, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeBetween(String value1, String value2) {
            addCriterion("elec_size between", value1, value2, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecSizeNotBetween(String value1, String value2) {
            addCriterion("elec_size not between", value1, value2, "elecSize");
            return (Criteria) this;
        }

        public Criteria andElecDesIsNull() {
            addCriterion("elec_des is null");
            return (Criteria) this;
        }

        public Criteria andElecDesIsNotNull() {
            addCriterion("elec_des is not null");
            return (Criteria) this;
        }

        public Criteria andElecDesEqualTo(String value) {
            addCriterion("elec_des =", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesNotEqualTo(String value) {
            addCriterion("elec_des <>", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesGreaterThan(String value) {
            addCriterion("elec_des >", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesGreaterThanOrEqualTo(String value) {
            addCriterion("elec_des >=", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesLessThan(String value) {
            addCriterion("elec_des <", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesLessThanOrEqualTo(String value) {
            addCriterion("elec_des <=", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesLike(String value) {
            addCriterion("elec_des like", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesNotLike(String value) {
            addCriterion("elec_des not like", value, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesIn(List<String> values) {
            addCriterion("elec_des in", values, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesNotIn(List<String> values) {
            addCriterion("elec_des not in", values, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesBetween(String value1, String value2) {
            addCriterion("elec_des between", value1, value2, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecDesNotBetween(String value1, String value2) {
            addCriterion("elec_des not between", value1, value2, "elecDes");
            return (Criteria) this;
        }

        public Criteria andElecPushIsNull() {
            addCriterion("elec_push is null");
            return (Criteria) this;
        }

        public Criteria andElecPushIsNotNull() {
            addCriterion("elec_push is not null");
            return (Criteria) this;
        }

        public Criteria andElecPushEqualTo(Integer value) {
            addCriterion("elec_push =", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushNotEqualTo(Integer value) {
            addCriterion("elec_push <>", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushGreaterThan(Integer value) {
            addCriterion("elec_push >", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushGreaterThanOrEqualTo(Integer value) {
            addCriterion("elec_push >=", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushLessThan(Integer value) {
            addCriterion("elec_push <", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushLessThanOrEqualTo(Integer value) {
            addCriterion("elec_push <=", value, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushIn(List<Integer> values) {
            addCriterion("elec_push in", values, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushNotIn(List<Integer> values) {
            addCriterion("elec_push not in", values, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushBetween(Integer value1, Integer value2) {
            addCriterion("elec_push between", value1, value2, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecPushNotBetween(Integer value1, Integer value2) {
            addCriterion("elec_push not between", value1, value2, "elecPush");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIsNull() {
            addCriterion("elec_linkman is null");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIsNotNull() {
            addCriterion("elec_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanEqualTo(String value) {
            addCriterion("elec_linkman =", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotEqualTo(String value) {
            addCriterion("elec_linkman <>", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanGreaterThan(String value) {
            addCriterion("elec_linkman >", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("elec_linkman >=", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLessThan(String value) {
            addCriterion("elec_linkman <", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLessThanOrEqualTo(String value) {
            addCriterion("elec_linkman <=", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLike(String value) {
            addCriterion("elec_linkman like", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotLike(String value) {
            addCriterion("elec_linkman not like", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIn(List<String> values) {
            addCriterion("elec_linkman in", values, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotIn(List<String> values) {
            addCriterion("elec_linkman not in", values, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanBetween(String value1, String value2) {
            addCriterion("elec_linkman between", value1, value2, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotBetween(String value1, String value2) {
            addCriterion("elec_linkman not between", value1, value2, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIsNull() {
            addCriterion("elec_phone is null");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIsNotNull() {
            addCriterion("elec_phone is not null");
            return (Criteria) this;
        }

        public Criteria andElecPhoneEqualTo(String value) {
            addCriterion("elec_phone =", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotEqualTo(String value) {
            addCriterion("elec_phone <>", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneGreaterThan(String value) {
            addCriterion("elec_phone >", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("elec_phone >=", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLessThan(String value) {
            addCriterion("elec_phone <", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLessThanOrEqualTo(String value) {
            addCriterion("elec_phone <=", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLike(String value) {
            addCriterion("elec_phone like", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotLike(String value) {
            addCriterion("elec_phone not like", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIn(List<String> values) {
            addCriterion("elec_phone in", values, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotIn(List<String> values) {
            addCriterion("elec_phone not in", values, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneBetween(String value1, String value2) {
            addCriterion("elec_phone between", value1, value2, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotBetween(String value1, String value2) {
            addCriterion("elec_phone not between", value1, value2, "elecPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_elec
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}