package com.wjp.fem.bean;

public class Electricity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_value
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer elecValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer elecEarly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer elecWarning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer foreSpotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecSpotDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecTexture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecSetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer elecPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_id
     *
     * @return the value of fire_elec.elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecId() {
        return elecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_id
     *
     * @param elecId the value for fire_elec.elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecId(String elecId) {
        this.elecId = elecId == null ? null : elecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_name
     *
     * @return the value of fire_elec.elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecName() {
        return elecName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_name
     *
     * @param elecName the value for fire_elec.elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecName(String elecName) {
        this.elecName = elecName == null ? null : elecName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_value
     *
     * @return the value of fire_elec.elec_value
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getElecValue() {
        return elecValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_value
     *
     * @param elecValue the value for fire_elec.elec_value
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecValue(Integer elecValue) {
        this.elecValue = elecValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_early
     *
     * @return the value of fire_elec.elec_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getElecEarly() {
        return elecEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_early
     *
     * @param elecEarly the value for fire_elec.elec_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecEarly(Integer elecEarly) {
        this.elecEarly = elecEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_warning
     *
     * @return the value of fire_elec.elec_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getElecWarning() {
        return elecWarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_warning
     *
     * @param elecWarning the value for fire_elec.elec_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecWarning(Integer elecWarning) {
        this.elecWarning = elecWarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_state
     *
     * @return the value of fire_elec.elec_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecState() {
        return elecState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_state
     *
     * @param elecState the value for fire_elec.elec_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecState(String elecState) {
        this.elecState = elecState == null ? null : elecState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.fore_spot_id
     *
     * @return the value of fire_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getForeSpotId() {
        return foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.fore_spot_id
     *
     * @param foreSpotId the value for fire_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotId(Integer foreSpotId) {
        this.foreSpotId = foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_spot_detail
     *
     * @return the value of fire_elec.elec_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecSpotDetail() {
        return elecSpotDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_spot_detail
     *
     * @param elecSpotDetail the value for fire_elec.elec_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecSpotDetail(String elecSpotDetail) {
        this.elecSpotDetail = elecSpotDetail == null ? null : elecSpotDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_standard
     *
     * @return the value of fire_elec.elec_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecStandard() {
        return elecStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_standard
     *
     * @param elecStandard the value for fire_elec.elec_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecStandard(String elecStandard) {
        this.elecStandard = elecStandard == null ? null : elecStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_voltage
     *
     * @return the value of fire_elec.elec_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecVoltage() {
        return elecVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_voltage
     *
     * @param elecVoltage the value for fire_elec.elec_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecVoltage(String elecVoltage) {
        this.elecVoltage = elecVoltage == null ? null : elecVoltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_current
     *
     * @return the value of fire_elec.elec_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecCurrent() {
        return elecCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_current
     *
     * @param elecCurrent the value for fire_elec.elec_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecCurrent(String elecCurrent) {
        this.elecCurrent = elecCurrent == null ? null : elecCurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_texture
     *
     * @return the value of fire_elec.elec_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecTexture() {
        return elecTexture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_texture
     *
     * @param elecTexture the value for fire_elec.elec_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecTexture(String elecTexture) {
        this.elecTexture = elecTexture == null ? null : elecTexture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_setting
     *
     * @return the value of fire_elec.elec_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecSetting() {
        return elecSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_setting
     *
     * @param elecSetting the value for fire_elec.elec_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecSetting(String elecSetting) {
        this.elecSetting = elecSetting == null ? null : elecSetting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_size
     *
     * @return the value of fire_elec.elec_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecSize() {
        return elecSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_size
     *
     * @param elecSize the value for fire_elec.elec_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecSize(String elecSize) {
        this.elecSize = elecSize == null ? null : elecSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_des
     *
     * @return the value of fire_elec.elec_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecDes() {
        return elecDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_des
     *
     * @param elecDes the value for fire_elec.elec_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecDes(String elecDes) {
        this.elecDes = elecDes == null ? null : elecDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_push
     *
     * @return the value of fire_elec.elec_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getElecPush() {
        return elecPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_push
     *
     * @param elecPush the value for fire_elec.elec_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecPush(Integer elecPush) {
        this.elecPush = elecPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_linkman
     *
     * @return the value of fire_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecLinkman() {
        return elecLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_linkman
     *
     * @param elecLinkman the value for fire_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecLinkman(String elecLinkman) {
        this.elecLinkman = elecLinkman == null ? null : elecLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_elec.elec_phone
     *
     * @return the value of fire_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecPhone() {
        return elecPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_elec.elec_phone
     *
     * @param elecPhone the value for fire_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecPhone(String elecPhone) {
        this.elecPhone = elecPhone == null ? null : elecPhone.trim();
    }
}