package com.wjp.fem.bean;

public class ForeUserSpot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fore_user_spot.id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fore_user_spot.fore_user_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fore_user_spot.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer foreSpotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fore_user_spot.id
     *
     * @return the value of fore_user_spot.id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fore_user_spot.id
     *
     * @param id the value for fore_user_spot.id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fore_user_spot.fore_user_id
     *
     * @return the value of fore_user_spot.fore_user_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeUserId() {
        return foreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fore_user_spot.fore_user_id
     *
     * @param foreUserId the value for fore_user_spot.fore_user_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeUserId(String foreUserId) {
        this.foreUserId = foreUserId == null ? null : foreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fore_user_spot.fore_spot_id
     *
     * @return the value of fore_user_spot.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getForeSpotId() {
        return foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fore_user_spot.fore_spot_id
     *
     * @param foreSpotId the value for fore_user_spot.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotId(Integer foreSpotId) {
        this.foreSpotId = foreSpotId;
    }
}