package com.wjp.fem.bean;

import java.util.ArrayList;
import java.util.List;

public class ForeUserSpotExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public ForeUserSpotExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andForeUserIdIsNull() {
            addCriterion("fore_user_id is null");
            return (Criteria) this;
        }

        public Criteria andForeUserIdIsNotNull() {
            addCriterion("fore_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeUserIdEqualTo(String value) {
            addCriterion("fore_user_id =", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdNotEqualTo(String value) {
            addCriterion("fore_user_id <>", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdGreaterThan(String value) {
            addCriterion("fore_user_id >", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("fore_user_id >=", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdLessThan(String value) {
            addCriterion("fore_user_id <", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdLessThanOrEqualTo(String value) {
            addCriterion("fore_user_id <=", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdLike(String value) {
            addCriterion("fore_user_id like", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdNotLike(String value) {
            addCriterion("fore_user_id not like", value, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdIn(List<String> values) {
            addCriterion("fore_user_id in", values, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdNotIn(List<String> values) {
            addCriterion("fore_user_id not in", values, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdBetween(String value1, String value2) {
            addCriterion("fore_user_id between", value1, value2, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeUserIdNotBetween(String value1, String value2) {
            addCriterion("fore_user_id not between", value1, value2, "foreUserId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNull() {
            addCriterion("fore_spot_id is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNotNull() {
            addCriterion("fore_spot_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdEqualTo(Integer value) {
            addCriterion("fore_spot_id =", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotEqualTo(Integer value) {
            addCriterion("fore_spot_id <>", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThan(Integer value) {
            addCriterion("fore_spot_id >", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id >=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThan(Integer value) {
            addCriterion("fore_spot_id <", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id <=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIn(List<Integer> values) {
            addCriterion("fore_spot_id in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotIn(List<Integer> values) {
            addCriterion("fore_spot_id not in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id not between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fore_user_spot
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fore_user_spot
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}