package com.wjp.fem.bean;

import java.util.Date;

public class RecordElec {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.record_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Long recordElecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer foreSpotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreSpotDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.fore_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreElecId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.fore_elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreElecName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer recordVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String elecPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.record_elec_id
     *
     * @return the value of fire_record_elec.record_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Long getRecordElecId() {
        return recordElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.record_elec_id
     *
     * @param recordElecId the value for fire_record_elec.record_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordElecId(Long recordElecId) {
        this.recordElecId = recordElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.fore_spot_id
     *
     * @return the value of fire_record_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getForeSpotId() {
        return foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.fore_spot_id
     *
     * @param foreSpotId the value for fire_record_elec.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotId(Integer foreSpotId) {
        this.foreSpotId = foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.fore_spot_detail
     *
     * @return the value of fire_record_elec.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeSpotDetail() {
        return foreSpotDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.fore_spot_detail
     *
     * @param foreSpotDetail the value for fire_record_elec.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotDetail(String foreSpotDetail) {
        this.foreSpotDetail = foreSpotDetail == null ? null : foreSpotDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.fore_elec_id
     *
     * @return the value of fire_record_elec.fore_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeElecId() {
        return foreElecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.fore_elec_id
     *
     * @param foreElecId the value for fire_record_elec.fore_elec_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeElecId(String foreElecId) {
        this.foreElecId = foreElecId == null ? null : foreElecId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.fore_elec_name
     *
     * @return the value of fire_record_elec.fore_elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeElecName() {
        return foreElecName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.fore_elec_name
     *
     * @param foreElecName the value for fire_record_elec.fore_elec_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeElecName(String foreElecName) {
        this.foreElecName = foreElecName == null ? null : foreElecName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.record_val
     *
     * @return the value of fire_record_elec.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getRecordVal() {
        return recordVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.record_val
     *
     * @param recordVal the value for fire_record_elec.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordVal(Integer recordVal) {
        this.recordVal = recordVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.record_time
     *
     * @return the value of fire_record_elec.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.record_time
     *
     * @param recordTime the value for fire_record_elec.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.record_state
     *
     * @return the value of fire_record_elec.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.record_state
     *
     * @param recordState the value for fire_record_elec.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState == null ? null : recordState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.elec_linkman
     *
     * @return the value of fire_record_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecLinkman() {
        return elecLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.elec_linkman
     *
     * @param elecLinkman the value for fire_record_elec.elec_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecLinkman(String elecLinkman) {
        this.elecLinkman = elecLinkman == null ? null : elecLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_elec.elec_phone
     *
     * @return the value of fire_record_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getElecPhone() {
        return elecPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_elec.elec_phone
     *
     * @param elecPhone the value for fire_record_elec.elec_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setElecPhone(String elecPhone) {
        this.elecPhone = elecPhone == null ? null : elecPhone.trim();
    }
}