package com.wjp.fem.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordTempExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public RecordTempExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordTempIdIsNull() {
            addCriterion("record_temp_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdIsNotNull() {
            addCriterion("record_temp_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdEqualTo(Long value) {
            addCriterion("record_temp_id =", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdNotEqualTo(Long value) {
            addCriterion("record_temp_id <>", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdGreaterThan(Long value) {
            addCriterion("record_temp_id >", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdGreaterThanOrEqualTo(Long value) {
            addCriterion("record_temp_id >=", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdLessThan(Long value) {
            addCriterion("record_temp_id <", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdLessThanOrEqualTo(Long value) {
            addCriterion("record_temp_id <=", value, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdIn(List<Long> values) {
            addCriterion("record_temp_id in", values, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdNotIn(List<Long> values) {
            addCriterion("record_temp_id not in", values, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdBetween(Long value1, Long value2) {
            addCriterion("record_temp_id between", value1, value2, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andRecordTempIdNotBetween(Long value1, Long value2) {
            addCriterion("record_temp_id not between", value1, value2, "recordTempId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNull() {
            addCriterion("fore_spot_id is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNotNull() {
            addCriterion("fore_spot_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdEqualTo(Integer value) {
            addCriterion("fore_spot_id =", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotEqualTo(Integer value) {
            addCriterion("fore_spot_id <>", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThan(Integer value) {
            addCriterion("fore_spot_id >", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id >=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThan(Integer value) {
            addCriterion("fore_spot_id <", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id <=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIn(List<Integer> values) {
            addCriterion("fore_spot_id in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotIn(List<Integer> values) {
            addCriterion("fore_spot_id not in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id not between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIsNull() {
            addCriterion("fore_spot_detail is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIsNotNull() {
            addCriterion("fore_spot_detail is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailEqualTo(String value) {
            addCriterion("fore_spot_detail =", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotEqualTo(String value) {
            addCriterion("fore_spot_detail <>", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailGreaterThan(String value) {
            addCriterion("fore_spot_detail >", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailGreaterThanOrEqualTo(String value) {
            addCriterion("fore_spot_detail >=", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLessThan(String value) {
            addCriterion("fore_spot_detail <", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLessThanOrEqualTo(String value) {
            addCriterion("fore_spot_detail <=", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLike(String value) {
            addCriterion("fore_spot_detail like", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotLike(String value) {
            addCriterion("fore_spot_detail not like", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIn(List<String> values) {
            addCriterion("fore_spot_detail in", values, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotIn(List<String> values) {
            addCriterion("fore_spot_detail not in", values, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailBetween(String value1, String value2) {
            addCriterion("fore_spot_detail between", value1, value2, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotBetween(String value1, String value2) {
            addCriterion("fore_spot_detail not between", value1, value2, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeTempIdIsNull() {
            addCriterion("fore_temp_id is null");
            return (Criteria) this;
        }

        public Criteria andForeTempIdIsNotNull() {
            addCriterion("fore_temp_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeTempIdEqualTo(String value) {
            addCriterion("fore_temp_id =", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdNotEqualTo(String value) {
            addCriterion("fore_temp_id <>", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdGreaterThan(String value) {
            addCriterion("fore_temp_id >", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdGreaterThanOrEqualTo(String value) {
            addCriterion("fore_temp_id >=", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdLessThan(String value) {
            addCriterion("fore_temp_id <", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdLessThanOrEqualTo(String value) {
            addCriterion("fore_temp_id <=", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdLike(String value) {
            addCriterion("fore_temp_id like", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdNotLike(String value) {
            addCriterion("fore_temp_id not like", value, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdIn(List<String> values) {
            addCriterion("fore_temp_id in", values, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdNotIn(List<String> values) {
            addCriterion("fore_temp_id not in", values, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdBetween(String value1, String value2) {
            addCriterion("fore_temp_id between", value1, value2, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempIdNotBetween(String value1, String value2) {
            addCriterion("fore_temp_id not between", value1, value2, "foreTempId");
            return (Criteria) this;
        }

        public Criteria andForeTempNameIsNull() {
            addCriterion("fore_temp_name is null");
            return (Criteria) this;
        }

        public Criteria andForeTempNameIsNotNull() {
            addCriterion("fore_temp_name is not null");
            return (Criteria) this;
        }

        public Criteria andForeTempNameEqualTo(String value) {
            addCriterion("fore_temp_name =", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameNotEqualTo(String value) {
            addCriterion("fore_temp_name <>", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameGreaterThan(String value) {
            addCriterion("fore_temp_name >", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameGreaterThanOrEqualTo(String value) {
            addCriterion("fore_temp_name >=", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameLessThan(String value) {
            addCriterion("fore_temp_name <", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameLessThanOrEqualTo(String value) {
            addCriterion("fore_temp_name <=", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameLike(String value) {
            addCriterion("fore_temp_name like", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameNotLike(String value) {
            addCriterion("fore_temp_name not like", value, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameIn(List<String> values) {
            addCriterion("fore_temp_name in", values, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameNotIn(List<String> values) {
            addCriterion("fore_temp_name not in", values, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameBetween(String value1, String value2) {
            addCriterion("fore_temp_name between", value1, value2, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andForeTempNameNotBetween(String value1, String value2) {
            addCriterion("fore_temp_name not between", value1, value2, "foreTempName");
            return (Criteria) this;
        }

        public Criteria andRecordValIsNull() {
            addCriterion("record_val is null");
            return (Criteria) this;
        }

        public Criteria andRecordValIsNotNull() {
            addCriterion("record_val is not null");
            return (Criteria) this;
        }

        public Criteria andRecordValEqualTo(Integer value) {
            addCriterion("record_val =", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotEqualTo(Integer value) {
            addCriterion("record_val <>", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValGreaterThan(Integer value) {
            addCriterion("record_val >", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_val >=", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValLessThan(Integer value) {
            addCriterion("record_val <", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValLessThanOrEqualTo(Integer value) {
            addCriterion("record_val <=", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValIn(List<Integer> values) {
            addCriterion("record_val in", values, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotIn(List<Integer> values) {
            addCriterion("record_val not in", values, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValBetween(Integer value1, Integer value2) {
            addCriterion("record_val between", value1, value2, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotBetween(Integer value1, Integer value2) {
            addCriterion("record_val not between", value1, value2, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNull() {
            addCriterion("record_time is null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNotNull() {
            addCriterion("record_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeEqualTo(Date value) {
            addCriterion("record_time =", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotEqualTo(Date value) {
            addCriterion("record_time <>", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThan(Date value) {
            addCriterion("record_time >", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("record_time >=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThan(Date value) {
            addCriterion("record_time <", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThanOrEqualTo(Date value) {
            addCriterion("record_time <=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIn(List<Date> values) {
            addCriterion("record_time in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotIn(List<Date> values) {
            addCriterion("record_time not in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeBetween(Date value1, Date value2) {
            addCriterion("record_time between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotBetween(Date value1, Date value2) {
            addCriterion("record_time not between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordStateIsNull() {
            addCriterion("record_state is null");
            return (Criteria) this;
        }

        public Criteria andRecordStateIsNotNull() {
            addCriterion("record_state is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStateEqualTo(String value) {
            addCriterion("record_state =", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotEqualTo(String value) {
            addCriterion("record_state <>", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateGreaterThan(String value) {
            addCriterion("record_state >", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateGreaterThanOrEqualTo(String value) {
            addCriterion("record_state >=", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLessThan(String value) {
            addCriterion("record_state <", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLessThanOrEqualTo(String value) {
            addCriterion("record_state <=", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLike(String value) {
            addCriterion("record_state like", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotLike(String value) {
            addCriterion("record_state not like", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateIn(List<String> values) {
            addCriterion("record_state in", values, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotIn(List<String> values) {
            addCriterion("record_state not in", values, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateBetween(String value1, String value2) {
            addCriterion("record_state between", value1, value2, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotBetween(String value1, String value2) {
            addCriterion("record_state not between", value1, value2, "recordState");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIsNull() {
            addCriterion("temp_linkman is null");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIsNotNull() {
            addCriterion("temp_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanEqualTo(String value) {
            addCriterion("temp_linkman =", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotEqualTo(String value) {
            addCriterion("temp_linkman <>", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanGreaterThan(String value) {
            addCriterion("temp_linkman >", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("temp_linkman >=", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLessThan(String value) {
            addCriterion("temp_linkman <", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLessThanOrEqualTo(String value) {
            addCriterion("temp_linkman <=", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLike(String value) {
            addCriterion("temp_linkman like", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotLike(String value) {
            addCriterion("temp_linkman not like", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIn(List<String> values) {
            addCriterion("temp_linkman in", values, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotIn(List<String> values) {
            addCriterion("temp_linkman not in", values, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanBetween(String value1, String value2) {
            addCriterion("temp_linkman between", value1, value2, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotBetween(String value1, String value2) {
            addCriterion("temp_linkman not between", value1, value2, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIsNull() {
            addCriterion("temp_phone is null");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIsNotNull() {
            addCriterion("temp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTempPhoneEqualTo(String value) {
            addCriterion("temp_phone =", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotEqualTo(String value) {
            addCriterion("temp_phone <>", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneGreaterThan(String value) {
            addCriterion("temp_phone >", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("temp_phone >=", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLessThan(String value) {
            addCriterion("temp_phone <", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLessThanOrEqualTo(String value) {
            addCriterion("temp_phone <=", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLike(String value) {
            addCriterion("temp_phone like", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotLike(String value) {
            addCriterion("temp_phone not like", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIn(List<String> values) {
            addCriterion("temp_phone in", values, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotIn(List<String> values) {
            addCriterion("temp_phone not in", values, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneBetween(String value1, String value2) {
            addCriterion("temp_phone between", value1, value2, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotBetween(String value1, String value2) {
            addCriterion("temp_phone not between", value1, value2, "tempPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_temp
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}