package com.wjp.fem.bean;

import java.util.Date;

public class RecordTemp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.record_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Long recordTempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer foreSpotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreSpotDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.fore_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreTempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.fore_temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String foreTempName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer recordVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String recordState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_record_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.record_temp_id
     *
     * @return the value of fire_record_temp.record_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Long getRecordTempId() {
        return recordTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.record_temp_id
     *
     * @param recordTempId the value for fire_record_temp.record_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordTempId(Long recordTempId) {
        this.recordTempId = recordTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.fore_spot_id
     *
     * @return the value of fire_record_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getForeSpotId() {
        return foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.fore_spot_id
     *
     * @param foreSpotId the value for fire_record_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotId(Integer foreSpotId) {
        this.foreSpotId = foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.fore_spot_detail
     *
     * @return the value of fire_record_temp.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeSpotDetail() {
        return foreSpotDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.fore_spot_detail
     *
     * @param foreSpotDetail the value for fire_record_temp.fore_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotDetail(String foreSpotDetail) {
        this.foreSpotDetail = foreSpotDetail == null ? null : foreSpotDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.fore_temp_id
     *
     * @return the value of fire_record_temp.fore_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeTempId() {
        return foreTempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.fore_temp_id
     *
     * @param foreTempId the value for fire_record_temp.fore_temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeTempId(String foreTempId) {
        this.foreTempId = foreTempId == null ? null : foreTempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.fore_temp_name
     *
     * @return the value of fire_record_temp.fore_temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getForeTempName() {
        return foreTempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.fore_temp_name
     *
     * @param foreTempName the value for fire_record_temp.fore_temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeTempName(String foreTempName) {
        this.foreTempName = foreTempName == null ? null : foreTempName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.record_val
     *
     * @return the value of fire_record_temp.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getRecordVal() {
        return recordVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.record_val
     *
     * @param recordVal the value for fire_record_temp.record_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordVal(Integer recordVal) {
        this.recordVal = recordVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.record_time
     *
     * @return the value of fire_record_temp.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.record_time
     *
     * @param recordTime the value for fire_record_temp.record_time
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.record_state
     *
     * @return the value of fire_record_temp.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.record_state
     *
     * @param recordState the value for fire_record_temp.record_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState == null ? null : recordState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.temp_linkman
     *
     * @return the value of fire_record_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempLinkman() {
        return tempLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.temp_linkman
     *
     * @param tempLinkman the value for fire_record_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempLinkman(String tempLinkman) {
        this.tempLinkman = tempLinkman == null ? null : tempLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_record_temp.temp_phone
     *
     * @return the value of fire_record_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempPhone() {
        return tempPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_record_temp.temp_phone
     *
     * @param tempPhone the value for fire_record_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempPhone(String tempPhone) {
        this.tempPhone = tempPhone == null ? null : tempPhone.trim();
    }
}