package com.wjp.fem.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordElecExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public RecordElecExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordElecIdIsNull() {
            addCriterion("record_elec_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdIsNotNull() {
            addCriterion("record_elec_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdEqualTo(Long value) {
            addCriterion("record_elec_id =", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdNotEqualTo(Long value) {
            addCriterion("record_elec_id <>", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdGreaterThan(Long value) {
            addCriterion("record_elec_id >", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdGreaterThanOrEqualTo(Long value) {
            addCriterion("record_elec_id >=", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdLessThan(Long value) {
            addCriterion("record_elec_id <", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdLessThanOrEqualTo(Long value) {
            addCriterion("record_elec_id <=", value, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdIn(List<Long> values) {
            addCriterion("record_elec_id in", values, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdNotIn(List<Long> values) {
            addCriterion("record_elec_id not in", values, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdBetween(Long value1, Long value2) {
            addCriterion("record_elec_id between", value1, value2, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andRecordElecIdNotBetween(Long value1, Long value2) {
            addCriterion("record_elec_id not between", value1, value2, "recordElecId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNull() {
            addCriterion("fore_spot_id is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNotNull() {
            addCriterion("fore_spot_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdEqualTo(Integer value) {
            addCriterion("fore_spot_id =", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotEqualTo(Integer value) {
            addCriterion("fore_spot_id <>", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThan(Integer value) {
            addCriterion("fore_spot_id >", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id >=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThan(Integer value) {
            addCriterion("fore_spot_id <", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id <=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIn(List<Integer> values) {
            addCriterion("fore_spot_id in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotIn(List<Integer> values) {
            addCriterion("fore_spot_id not in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id not between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIsNull() {
            addCriterion("fore_spot_detail is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIsNotNull() {
            addCriterion("fore_spot_detail is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailEqualTo(String value) {
            addCriterion("fore_spot_detail =", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotEqualTo(String value) {
            addCriterion("fore_spot_detail <>", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailGreaterThan(String value) {
            addCriterion("fore_spot_detail >", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailGreaterThanOrEqualTo(String value) {
            addCriterion("fore_spot_detail >=", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLessThan(String value) {
            addCriterion("fore_spot_detail <", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLessThanOrEqualTo(String value) {
            addCriterion("fore_spot_detail <=", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailLike(String value) {
            addCriterion("fore_spot_detail like", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotLike(String value) {
            addCriterion("fore_spot_detail not like", value, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailIn(List<String> values) {
            addCriterion("fore_spot_detail in", values, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotIn(List<String> values) {
            addCriterion("fore_spot_detail not in", values, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailBetween(String value1, String value2) {
            addCriterion("fore_spot_detail between", value1, value2, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeSpotDetailNotBetween(String value1, String value2) {
            addCriterion("fore_spot_detail not between", value1, value2, "foreSpotDetail");
            return (Criteria) this;
        }

        public Criteria andForeElecIdIsNull() {
            addCriterion("fore_elec_id is null");
            return (Criteria) this;
        }

        public Criteria andForeElecIdIsNotNull() {
            addCriterion("fore_elec_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeElecIdEqualTo(String value) {
            addCriterion("fore_elec_id =", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdNotEqualTo(String value) {
            addCriterion("fore_elec_id <>", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdGreaterThan(String value) {
            addCriterion("fore_elec_id >", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdGreaterThanOrEqualTo(String value) {
            addCriterion("fore_elec_id >=", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdLessThan(String value) {
            addCriterion("fore_elec_id <", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdLessThanOrEqualTo(String value) {
            addCriterion("fore_elec_id <=", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdLike(String value) {
            addCriterion("fore_elec_id like", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdNotLike(String value) {
            addCriterion("fore_elec_id not like", value, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdIn(List<String> values) {
            addCriterion("fore_elec_id in", values, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdNotIn(List<String> values) {
            addCriterion("fore_elec_id not in", values, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdBetween(String value1, String value2) {
            addCriterion("fore_elec_id between", value1, value2, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecIdNotBetween(String value1, String value2) {
            addCriterion("fore_elec_id not between", value1, value2, "foreElecId");
            return (Criteria) this;
        }

        public Criteria andForeElecNameIsNull() {
            addCriterion("fore_elec_name is null");
            return (Criteria) this;
        }

        public Criteria andForeElecNameIsNotNull() {
            addCriterion("fore_elec_name is not null");
            return (Criteria) this;
        }

        public Criteria andForeElecNameEqualTo(String value) {
            addCriterion("fore_elec_name =", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameNotEqualTo(String value) {
            addCriterion("fore_elec_name <>", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameGreaterThan(String value) {
            addCriterion("fore_elec_name >", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameGreaterThanOrEqualTo(String value) {
            addCriterion("fore_elec_name >=", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameLessThan(String value) {
            addCriterion("fore_elec_name <", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameLessThanOrEqualTo(String value) {
            addCriterion("fore_elec_name <=", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameLike(String value) {
            addCriterion("fore_elec_name like", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameNotLike(String value) {
            addCriterion("fore_elec_name not like", value, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameIn(List<String> values) {
            addCriterion("fore_elec_name in", values, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameNotIn(List<String> values) {
            addCriterion("fore_elec_name not in", values, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameBetween(String value1, String value2) {
            addCriterion("fore_elec_name between", value1, value2, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andForeElecNameNotBetween(String value1, String value2) {
            addCriterion("fore_elec_name not between", value1, value2, "foreElecName");
            return (Criteria) this;
        }

        public Criteria andRecordValIsNull() {
            addCriterion("record_val is null");
            return (Criteria) this;
        }

        public Criteria andRecordValIsNotNull() {
            addCriterion("record_val is not null");
            return (Criteria) this;
        }

        public Criteria andRecordValEqualTo(Integer value) {
            addCriterion("record_val =", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotEqualTo(Integer value) {
            addCriterion("record_val <>", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValGreaterThan(Integer value) {
            addCriterion("record_val >", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_val >=", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValLessThan(Integer value) {
            addCriterion("record_val <", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValLessThanOrEqualTo(Integer value) {
            addCriterion("record_val <=", value, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValIn(List<Integer> values) {
            addCriterion("record_val in", values, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotIn(List<Integer> values) {
            addCriterion("record_val not in", values, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValBetween(Integer value1, Integer value2) {
            addCriterion("record_val between", value1, value2, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordValNotBetween(Integer value1, Integer value2) {
            addCriterion("record_val not between", value1, value2, "recordVal");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNull() {
            addCriterion("record_time is null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIsNotNull() {
            addCriterion("record_time is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTimeEqualTo(Date value) {
            addCriterion("record_time =", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotEqualTo(Date value) {
            addCriterion("record_time <>", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThan(Date value) {
            addCriterion("record_time >", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("record_time >=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThan(Date value) {
            addCriterion("record_time <", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeLessThanOrEqualTo(Date value) {
            addCriterion("record_time <=", value, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeIn(List<Date> values) {
            addCriterion("record_time in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotIn(List<Date> values) {
            addCriterion("record_time not in", values, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeBetween(Date value1, Date value2) {
            addCriterion("record_time between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordTimeNotBetween(Date value1, Date value2) {
            addCriterion("record_time not between", value1, value2, "recordTime");
            return (Criteria) this;
        }

        public Criteria andRecordStateIsNull() {
            addCriterion("record_state is null");
            return (Criteria) this;
        }

        public Criteria andRecordStateIsNotNull() {
            addCriterion("record_state is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStateEqualTo(String value) {
            addCriterion("record_state =", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotEqualTo(String value) {
            addCriterion("record_state <>", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateGreaterThan(String value) {
            addCriterion("record_state >", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateGreaterThanOrEqualTo(String value) {
            addCriterion("record_state >=", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLessThan(String value) {
            addCriterion("record_state <", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLessThanOrEqualTo(String value) {
            addCriterion("record_state <=", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateLike(String value) {
            addCriterion("record_state like", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotLike(String value) {
            addCriterion("record_state not like", value, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateIn(List<String> values) {
            addCriterion("record_state in", values, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotIn(List<String> values) {
            addCriterion("record_state not in", values, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateBetween(String value1, String value2) {
            addCriterion("record_state between", value1, value2, "recordState");
            return (Criteria) this;
        }

        public Criteria andRecordStateNotBetween(String value1, String value2) {
            addCriterion("record_state not between", value1, value2, "recordState");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIsNull() {
            addCriterion("elec_linkman is null");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIsNotNull() {
            addCriterion("elec_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanEqualTo(String value) {
            addCriterion("elec_linkman =", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotEqualTo(String value) {
            addCriterion("elec_linkman <>", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanGreaterThan(String value) {
            addCriterion("elec_linkman >", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("elec_linkman >=", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLessThan(String value) {
            addCriterion("elec_linkman <", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLessThanOrEqualTo(String value) {
            addCriterion("elec_linkman <=", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanLike(String value) {
            addCriterion("elec_linkman like", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotLike(String value) {
            addCriterion("elec_linkman not like", value, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanIn(List<String> values) {
            addCriterion("elec_linkman in", values, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotIn(List<String> values) {
            addCriterion("elec_linkman not in", values, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanBetween(String value1, String value2) {
            addCriterion("elec_linkman between", value1, value2, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecLinkmanNotBetween(String value1, String value2) {
            addCriterion("elec_linkman not between", value1, value2, "elecLinkman");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIsNull() {
            addCriterion("elec_phone is null");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIsNotNull() {
            addCriterion("elec_phone is not null");
            return (Criteria) this;
        }

        public Criteria andElecPhoneEqualTo(String value) {
            addCriterion("elec_phone =", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotEqualTo(String value) {
            addCriterion("elec_phone <>", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneGreaterThan(String value) {
            addCriterion("elec_phone >", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("elec_phone >=", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLessThan(String value) {
            addCriterion("elec_phone <", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLessThanOrEqualTo(String value) {
            addCriterion("elec_phone <=", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneLike(String value) {
            addCriterion("elec_phone like", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotLike(String value) {
            addCriterion("elec_phone not like", value, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneIn(List<String> values) {
            addCriterion("elec_phone in", values, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotIn(List<String> values) {
            addCriterion("elec_phone not in", values, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneBetween(String value1, String value2) {
            addCriterion("elec_phone between", value1, value2, "elecPhone");
            return (Criteria) this;
        }

        public Criteria andElecPhoneNotBetween(String value1, String value2) {
            addCriterion("elec_phone not between", value1, value2, "elecPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_elec
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_record_elec
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}