package com.wjp.fem.bean;

public class Spot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer spotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String spotState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_city
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String spotCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_county
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String spotCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_category
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String spotCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_spot.spot_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String spotName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_id
     *
     * @return the value of fire_spot.spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getSpotId() {
        return spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_id
     *
     * @param spotId the value for fire_spot.spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotId(Integer spotId) {
        this.spotId = spotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_state
     *
     * @return the value of fire_spot.spot_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getSpotState() {
        return spotState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_state
     *
     * @param spotState the value for fire_spot.spot_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotState(String spotState) {
        this.spotState = spotState == null ? null : spotState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_city
     *
     * @return the value of fire_spot.spot_city
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getSpotCity() {
        return spotCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_city
     *
     * @param spotCity the value for fire_spot.spot_city
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotCity(String spotCity) {
        this.spotCity = spotCity == null ? null : spotCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_county
     *
     * @return the value of fire_spot.spot_county
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getSpotCounty() {
        return spotCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_county
     *
     * @param spotCounty the value for fire_spot.spot_county
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotCounty(String spotCounty) {
        this.spotCounty = spotCounty == null ? null : spotCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_category
     *
     * @return the value of fire_spot.spot_category
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getSpotCategory() {
        return spotCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_category
     *
     * @param spotCategory the value for fire_spot.spot_category
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotCategory(String spotCategory) {
        this.spotCategory = spotCategory == null ? null : spotCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_spot.spot_name
     *
     * @return the value of fire_spot.spot_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getSpotName() {
        return spotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_spot.spot_name
     *
     * @param spotName the value for fire_spot.spot_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setSpotName(String spotName) {
        this.spotName = spotName == null ? null : spotName.trim();
    }
}