package com.wjp.fem.bean;

import java.util.ArrayList;
import java.util.List;

public class TemperatureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public TemperatureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTempIdIsNull() {
            addCriterion("temp_id is null");
            return (Criteria) this;
        }

        public Criteria andTempIdIsNotNull() {
            addCriterion("temp_id is not null");
            return (Criteria) this;
        }

        public Criteria andTempIdEqualTo(String value) {
            addCriterion("temp_id =", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotEqualTo(String value) {
            addCriterion("temp_id <>", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThan(String value) {
            addCriterion("temp_id >", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThanOrEqualTo(String value) {
            addCriterion("temp_id >=", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThan(String value) {
            addCriterion("temp_id <", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThanOrEqualTo(String value) {
            addCriterion("temp_id <=", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLike(String value) {
            addCriterion("temp_id like", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotLike(String value) {
            addCriterion("temp_id not like", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdIn(List<String> values) {
            addCriterion("temp_id in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotIn(List<String> values) {
            addCriterion("temp_id not in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdBetween(String value1, String value2) {
            addCriterion("temp_id between", value1, value2, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotBetween(String value1, String value2) {
            addCriterion("temp_id not between", value1, value2, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempNameIsNull() {
            addCriterion("temp_name is null");
            return (Criteria) this;
        }

        public Criteria andTempNameIsNotNull() {
            addCriterion("temp_name is not null");
            return (Criteria) this;
        }

        public Criteria andTempNameEqualTo(String value) {
            addCriterion("temp_name =", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameNotEqualTo(String value) {
            addCriterion("temp_name <>", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameGreaterThan(String value) {
            addCriterion("temp_name >", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameGreaterThanOrEqualTo(String value) {
            addCriterion("temp_name >=", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameLessThan(String value) {
            addCriterion("temp_name <", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameLessThanOrEqualTo(String value) {
            addCriterion("temp_name <=", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameLike(String value) {
            addCriterion("temp_name like", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameNotLike(String value) {
            addCriterion("temp_name not like", value, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameIn(List<String> values) {
            addCriterion("temp_name in", values, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameNotIn(List<String> values) {
            addCriterion("temp_name not in", values, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameBetween(String value1, String value2) {
            addCriterion("temp_name between", value1, value2, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempNameNotBetween(String value1, String value2) {
            addCriterion("temp_name not between", value1, value2, "tempName");
            return (Criteria) this;
        }

        public Criteria andTempValIsNull() {
            addCriterion("temp_val is null");
            return (Criteria) this;
        }

        public Criteria andTempValIsNotNull() {
            addCriterion("temp_val is not null");
            return (Criteria) this;
        }

        public Criteria andTempValEqualTo(Integer value) {
            addCriterion("temp_val =", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValNotEqualTo(Integer value) {
            addCriterion("temp_val <>", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValGreaterThan(Integer value) {
            addCriterion("temp_val >", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_val >=", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValLessThan(Integer value) {
            addCriterion("temp_val <", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValLessThanOrEqualTo(Integer value) {
            addCriterion("temp_val <=", value, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValIn(List<Integer> values) {
            addCriterion("temp_val in", values, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValNotIn(List<Integer> values) {
            addCriterion("temp_val not in", values, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValBetween(Integer value1, Integer value2) {
            addCriterion("temp_val between", value1, value2, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempValNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_val not between", value1, value2, "tempVal");
            return (Criteria) this;
        }

        public Criteria andTempEarlyIsNull() {
            addCriterion("temp_early is null");
            return (Criteria) this;
        }

        public Criteria andTempEarlyIsNotNull() {
            addCriterion("temp_early is not null");
            return (Criteria) this;
        }

        public Criteria andTempEarlyEqualTo(Integer value) {
            addCriterion("temp_early =", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyNotEqualTo(Integer value) {
            addCriterion("temp_early <>", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyGreaterThan(Integer value) {
            addCriterion("temp_early >", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_early >=", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyLessThan(Integer value) {
            addCriterion("temp_early <", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyLessThanOrEqualTo(Integer value) {
            addCriterion("temp_early <=", value, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyIn(List<Integer> values) {
            addCriterion("temp_early in", values, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyNotIn(List<Integer> values) {
            addCriterion("temp_early not in", values, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyBetween(Integer value1, Integer value2) {
            addCriterion("temp_early between", value1, value2, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempEarlyNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_early not between", value1, value2, "tempEarly");
            return (Criteria) this;
        }

        public Criteria andTempWarningIsNull() {
            addCriterion("temp_warning is null");
            return (Criteria) this;
        }

        public Criteria andTempWarningIsNotNull() {
            addCriterion("temp_warning is not null");
            return (Criteria) this;
        }

        public Criteria andTempWarningEqualTo(Integer value) {
            addCriterion("temp_warning =", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningNotEqualTo(Integer value) {
            addCriterion("temp_warning <>", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningGreaterThan(Integer value) {
            addCriterion("temp_warning >", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_warning >=", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningLessThan(Integer value) {
            addCriterion("temp_warning <", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningLessThanOrEqualTo(Integer value) {
            addCriterion("temp_warning <=", value, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningIn(List<Integer> values) {
            addCriterion("temp_warning in", values, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningNotIn(List<Integer> values) {
            addCriterion("temp_warning not in", values, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningBetween(Integer value1, Integer value2) {
            addCriterion("temp_warning between", value1, value2, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempWarningNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_warning not between", value1, value2, "tempWarning");
            return (Criteria) this;
        }

        public Criteria andTempStateIsNull() {
            addCriterion("temp_state is null");
            return (Criteria) this;
        }

        public Criteria andTempStateIsNotNull() {
            addCriterion("temp_state is not null");
            return (Criteria) this;
        }

        public Criteria andTempStateEqualTo(String value) {
            addCriterion("temp_state =", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateNotEqualTo(String value) {
            addCriterion("temp_state <>", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateGreaterThan(String value) {
            addCriterion("temp_state >", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateGreaterThanOrEqualTo(String value) {
            addCriterion("temp_state >=", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateLessThan(String value) {
            addCriterion("temp_state <", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateLessThanOrEqualTo(String value) {
            addCriterion("temp_state <=", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateLike(String value) {
            addCriterion("temp_state like", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateNotLike(String value) {
            addCriterion("temp_state not like", value, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateIn(List<String> values) {
            addCriterion("temp_state in", values, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateNotIn(List<String> values) {
            addCriterion("temp_state not in", values, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateBetween(String value1, String value2) {
            addCriterion("temp_state between", value1, value2, "tempState");
            return (Criteria) this;
        }

        public Criteria andTempStateNotBetween(String value1, String value2) {
            addCriterion("temp_state not between", value1, value2, "tempState");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNull() {
            addCriterion("fore_spot_id is null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIsNotNull() {
            addCriterion("fore_spot_id is not null");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdEqualTo(Integer value) {
            addCriterion("fore_spot_id =", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotEqualTo(Integer value) {
            addCriterion("fore_spot_id <>", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThan(Integer value) {
            addCriterion("fore_spot_id >", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id >=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThan(Integer value) {
            addCriterion("fore_spot_id <", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdLessThanOrEqualTo(Integer value) {
            addCriterion("fore_spot_id <=", value, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdIn(List<Integer> values) {
            addCriterion("fore_spot_id in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotIn(List<Integer> values) {
            addCriterion("fore_spot_id not in", values, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andForeSpotIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fore_spot_id not between", value1, value2, "foreSpotId");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailIsNull() {
            addCriterion("temp_spot_detail is null");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailIsNotNull() {
            addCriterion("temp_spot_detail is not null");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailEqualTo(String value) {
            addCriterion("temp_spot_detail =", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailNotEqualTo(String value) {
            addCriterion("temp_spot_detail <>", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailGreaterThan(String value) {
            addCriterion("temp_spot_detail >", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailGreaterThanOrEqualTo(String value) {
            addCriterion("temp_spot_detail >=", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailLessThan(String value) {
            addCriterion("temp_spot_detail <", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailLessThanOrEqualTo(String value) {
            addCriterion("temp_spot_detail <=", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailLike(String value) {
            addCriterion("temp_spot_detail like", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailNotLike(String value) {
            addCriterion("temp_spot_detail not like", value, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailIn(List<String> values) {
            addCriterion("temp_spot_detail in", values, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailNotIn(List<String> values) {
            addCriterion("temp_spot_detail not in", values, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailBetween(String value1, String value2) {
            addCriterion("temp_spot_detail between", value1, value2, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempSpotDetailNotBetween(String value1, String value2) {
            addCriterion("temp_spot_detail not between", value1, value2, "tempSpotDetail");
            return (Criteria) this;
        }

        public Criteria andTempStandardIsNull() {
            addCriterion("temp_standard is null");
            return (Criteria) this;
        }

        public Criteria andTempStandardIsNotNull() {
            addCriterion("temp_standard is not null");
            return (Criteria) this;
        }

        public Criteria andTempStandardEqualTo(String value) {
            addCriterion("temp_standard =", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardNotEqualTo(String value) {
            addCriterion("temp_standard <>", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardGreaterThan(String value) {
            addCriterion("temp_standard >", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardGreaterThanOrEqualTo(String value) {
            addCriterion("temp_standard >=", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardLessThan(String value) {
            addCriterion("temp_standard <", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardLessThanOrEqualTo(String value) {
            addCriterion("temp_standard <=", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardLike(String value) {
            addCriterion("temp_standard like", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardNotLike(String value) {
            addCriterion("temp_standard not like", value, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardIn(List<String> values) {
            addCriterion("temp_standard in", values, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardNotIn(List<String> values) {
            addCriterion("temp_standard not in", values, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardBetween(String value1, String value2) {
            addCriterion("temp_standard between", value1, value2, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempStandardNotBetween(String value1, String value2) {
            addCriterion("temp_standard not between", value1, value2, "tempStandard");
            return (Criteria) this;
        }

        public Criteria andTempVoltageIsNull() {
            addCriterion("temp_voltage is null");
            return (Criteria) this;
        }

        public Criteria andTempVoltageIsNotNull() {
            addCriterion("temp_voltage is not null");
            return (Criteria) this;
        }

        public Criteria andTempVoltageEqualTo(String value) {
            addCriterion("temp_voltage =", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageNotEqualTo(String value) {
            addCriterion("temp_voltage <>", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageGreaterThan(String value) {
            addCriterion("temp_voltage >", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageGreaterThanOrEqualTo(String value) {
            addCriterion("temp_voltage >=", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageLessThan(String value) {
            addCriterion("temp_voltage <", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageLessThanOrEqualTo(String value) {
            addCriterion("temp_voltage <=", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageLike(String value) {
            addCriterion("temp_voltage like", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageNotLike(String value) {
            addCriterion("temp_voltage not like", value, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageIn(List<String> values) {
            addCriterion("temp_voltage in", values, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageNotIn(List<String> values) {
            addCriterion("temp_voltage not in", values, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageBetween(String value1, String value2) {
            addCriterion("temp_voltage between", value1, value2, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempVoltageNotBetween(String value1, String value2) {
            addCriterion("temp_voltage not between", value1, value2, "tempVoltage");
            return (Criteria) this;
        }

        public Criteria andTempCurrentIsNull() {
            addCriterion("temp_current is null");
            return (Criteria) this;
        }

        public Criteria andTempCurrentIsNotNull() {
            addCriterion("temp_current is not null");
            return (Criteria) this;
        }

        public Criteria andTempCurrentEqualTo(String value) {
            addCriterion("temp_current =", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentNotEqualTo(String value) {
            addCriterion("temp_current <>", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentGreaterThan(String value) {
            addCriterion("temp_current >", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentGreaterThanOrEqualTo(String value) {
            addCriterion("temp_current >=", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentLessThan(String value) {
            addCriterion("temp_current <", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentLessThanOrEqualTo(String value) {
            addCriterion("temp_current <=", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentLike(String value) {
            addCriterion("temp_current like", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentNotLike(String value) {
            addCriterion("temp_current not like", value, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentIn(List<String> values) {
            addCriterion("temp_current in", values, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentNotIn(List<String> values) {
            addCriterion("temp_current not in", values, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentBetween(String value1, String value2) {
            addCriterion("temp_current between", value1, value2, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempCurrentNotBetween(String value1, String value2) {
            addCriterion("temp_current not between", value1, value2, "tempCurrent");
            return (Criteria) this;
        }

        public Criteria andTempTextureIsNull() {
            addCriterion("temp_texture is null");
            return (Criteria) this;
        }

        public Criteria andTempTextureIsNotNull() {
            addCriterion("temp_texture is not null");
            return (Criteria) this;
        }

        public Criteria andTempTextureEqualTo(String value) {
            addCriterion("temp_texture =", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureNotEqualTo(String value) {
            addCriterion("temp_texture <>", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureGreaterThan(String value) {
            addCriterion("temp_texture >", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureGreaterThanOrEqualTo(String value) {
            addCriterion("temp_texture >=", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureLessThan(String value) {
            addCriterion("temp_texture <", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureLessThanOrEqualTo(String value) {
            addCriterion("temp_texture <=", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureLike(String value) {
            addCriterion("temp_texture like", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureNotLike(String value) {
            addCriterion("temp_texture not like", value, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureIn(List<String> values) {
            addCriterion("temp_texture in", values, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureNotIn(List<String> values) {
            addCriterion("temp_texture not in", values, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureBetween(String value1, String value2) {
            addCriterion("temp_texture between", value1, value2, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempTextureNotBetween(String value1, String value2) {
            addCriterion("temp_texture not between", value1, value2, "tempTexture");
            return (Criteria) this;
        }

        public Criteria andTempSettingIsNull() {
            addCriterion("temp_setting is null");
            return (Criteria) this;
        }

        public Criteria andTempSettingIsNotNull() {
            addCriterion("temp_setting is not null");
            return (Criteria) this;
        }

        public Criteria andTempSettingEqualTo(String value) {
            addCriterion("temp_setting =", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingNotEqualTo(String value) {
            addCriterion("temp_setting <>", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingGreaterThan(String value) {
            addCriterion("temp_setting >", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingGreaterThanOrEqualTo(String value) {
            addCriterion("temp_setting >=", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingLessThan(String value) {
            addCriterion("temp_setting <", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingLessThanOrEqualTo(String value) {
            addCriterion("temp_setting <=", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingLike(String value) {
            addCriterion("temp_setting like", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingNotLike(String value) {
            addCriterion("temp_setting not like", value, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingIn(List<String> values) {
            addCriterion("temp_setting in", values, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingNotIn(List<String> values) {
            addCriterion("temp_setting not in", values, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingBetween(String value1, String value2) {
            addCriterion("temp_setting between", value1, value2, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSettingNotBetween(String value1, String value2) {
            addCriterion("temp_setting not between", value1, value2, "tempSetting");
            return (Criteria) this;
        }

        public Criteria andTempSizeIsNull() {
            addCriterion("temp_size is null");
            return (Criteria) this;
        }

        public Criteria andTempSizeIsNotNull() {
            addCriterion("temp_size is not null");
            return (Criteria) this;
        }

        public Criteria andTempSizeEqualTo(String value) {
            addCriterion("temp_size =", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeNotEqualTo(String value) {
            addCriterion("temp_size <>", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeGreaterThan(String value) {
            addCriterion("temp_size >", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeGreaterThanOrEqualTo(String value) {
            addCriterion("temp_size >=", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeLessThan(String value) {
            addCriterion("temp_size <", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeLessThanOrEqualTo(String value) {
            addCriterion("temp_size <=", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeLike(String value) {
            addCriterion("temp_size like", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeNotLike(String value) {
            addCriterion("temp_size not like", value, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeIn(List<String> values) {
            addCriterion("temp_size in", values, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeNotIn(List<String> values) {
            addCriterion("temp_size not in", values, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeBetween(String value1, String value2) {
            addCriterion("temp_size between", value1, value2, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempSizeNotBetween(String value1, String value2) {
            addCriterion("temp_size not between", value1, value2, "tempSize");
            return (Criteria) this;
        }

        public Criteria andTempDesIsNull() {
            addCriterion("temp_des is null");
            return (Criteria) this;
        }

        public Criteria andTempDesIsNotNull() {
            addCriterion("temp_des is not null");
            return (Criteria) this;
        }

        public Criteria andTempDesEqualTo(String value) {
            addCriterion("temp_des =", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesNotEqualTo(String value) {
            addCriterion("temp_des <>", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesGreaterThan(String value) {
            addCriterion("temp_des >", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesGreaterThanOrEqualTo(String value) {
            addCriterion("temp_des >=", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesLessThan(String value) {
            addCriterion("temp_des <", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesLessThanOrEqualTo(String value) {
            addCriterion("temp_des <=", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesLike(String value) {
            addCriterion("temp_des like", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesNotLike(String value) {
            addCriterion("temp_des not like", value, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesIn(List<String> values) {
            addCriterion("temp_des in", values, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesNotIn(List<String> values) {
            addCriterion("temp_des not in", values, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesBetween(String value1, String value2) {
            addCriterion("temp_des between", value1, value2, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempDesNotBetween(String value1, String value2) {
            addCriterion("temp_des not between", value1, value2, "tempDes");
            return (Criteria) this;
        }

        public Criteria andTempPushIsNull() {
            addCriterion("temp_push is null");
            return (Criteria) this;
        }

        public Criteria andTempPushIsNotNull() {
            addCriterion("temp_push is not null");
            return (Criteria) this;
        }

        public Criteria andTempPushEqualTo(Integer value) {
            addCriterion("temp_push =", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushNotEqualTo(Integer value) {
            addCriterion("temp_push <>", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushGreaterThan(Integer value) {
            addCriterion("temp_push >", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_push >=", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushLessThan(Integer value) {
            addCriterion("temp_push <", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushLessThanOrEqualTo(Integer value) {
            addCriterion("temp_push <=", value, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushIn(List<Integer> values) {
            addCriterion("temp_push in", values, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushNotIn(List<Integer> values) {
            addCriterion("temp_push not in", values, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushBetween(Integer value1, Integer value2) {
            addCriterion("temp_push between", value1, value2, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempPushNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_push not between", value1, value2, "tempPush");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIsNull() {
            addCriterion("temp_linkman is null");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIsNotNull() {
            addCriterion("temp_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanEqualTo(String value) {
            addCriterion("temp_linkman =", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotEqualTo(String value) {
            addCriterion("temp_linkman <>", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanGreaterThan(String value) {
            addCriterion("temp_linkman >", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("temp_linkman >=", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLessThan(String value) {
            addCriterion("temp_linkman <", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLessThanOrEqualTo(String value) {
            addCriterion("temp_linkman <=", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanLike(String value) {
            addCriterion("temp_linkman like", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotLike(String value) {
            addCriterion("temp_linkman not like", value, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanIn(List<String> values) {
            addCriterion("temp_linkman in", values, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotIn(List<String> values) {
            addCriterion("temp_linkman not in", values, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanBetween(String value1, String value2) {
            addCriterion("temp_linkman between", value1, value2, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempLinkmanNotBetween(String value1, String value2) {
            addCriterion("temp_linkman not between", value1, value2, "tempLinkman");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIsNull() {
            addCriterion("temp_phone is null");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIsNotNull() {
            addCriterion("temp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTempPhoneEqualTo(String value) {
            addCriterion("temp_phone =", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotEqualTo(String value) {
            addCriterion("temp_phone <>", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneGreaterThan(String value) {
            addCriterion("temp_phone >", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("temp_phone >=", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLessThan(String value) {
            addCriterion("temp_phone <", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLessThanOrEqualTo(String value) {
            addCriterion("temp_phone <=", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneLike(String value) {
            addCriterion("temp_phone like", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotLike(String value) {
            addCriterion("temp_phone not like", value, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneIn(List<String> values) {
            addCriterion("temp_phone in", values, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotIn(List<String> values) {
            addCriterion("temp_phone not in", values, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneBetween(String value1, String value2) {
            addCriterion("temp_phone between", value1, value2, "tempPhone");
            return (Criteria) this;
        }

        public Criteria andTempPhoneNotBetween(String value1, String value2) {
            addCriterion("temp_phone not between", value1, value2, "tempPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_temp
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table fire_temp
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}