package com.wjp.fem.bean;

public class Temperature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer tempVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer tempEarly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer tempWarning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer foreSpotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempSpotDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempStandard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempVoltage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempTexture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempSetting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private Integer tempPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fire_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    private String tempPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_id
     *
     * @return the value of fire_temp.temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_id
     *
     * @param tempId the value for fire_temp.temp_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempId(String tempId) {
        this.tempId = tempId == null ? null : tempId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_name
     *
     * @return the value of fire_temp.temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempName() {
        return tempName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_name
     *
     * @param tempName the value for fire_temp.temp_name
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempName(String tempName) {
        this.tempName = tempName == null ? null : tempName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_val
     *
     * @return the value of fire_temp.temp_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getTempVal() {
        return tempVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_val
     *
     * @param tempVal the value for fire_temp.temp_val
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempVal(Integer tempVal) {
        this.tempVal = tempVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_early
     *
     * @return the value of fire_temp.temp_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getTempEarly() {
        return tempEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_early
     *
     * @param tempEarly the value for fire_temp.temp_early
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempEarly(Integer tempEarly) {
        this.tempEarly = tempEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_warning
     *
     * @return the value of fire_temp.temp_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getTempWarning() {
        return tempWarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_warning
     *
     * @param tempWarning the value for fire_temp.temp_warning
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempWarning(Integer tempWarning) {
        this.tempWarning = tempWarning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_state
     *
     * @return the value of fire_temp.temp_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempState() {
        return tempState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_state
     *
     * @param tempState the value for fire_temp.temp_state
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempState(String tempState) {
        this.tempState = tempState == null ? null : tempState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.fore_spot_id
     *
     * @return the value of fire_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getForeSpotId() {
        return foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.fore_spot_id
     *
     * @param foreSpotId the value for fire_temp.fore_spot_id
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setForeSpotId(Integer foreSpotId) {
        this.foreSpotId = foreSpotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_spot_detail
     *
     * @return the value of fire_temp.temp_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempSpotDetail() {
        return tempSpotDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_spot_detail
     *
     * @param tempSpotDetail the value for fire_temp.temp_spot_detail
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempSpotDetail(String tempSpotDetail) {
        this.tempSpotDetail = tempSpotDetail == null ? null : tempSpotDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_standard
     *
     * @return the value of fire_temp.temp_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempStandard() {
        return tempStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_standard
     *
     * @param tempStandard the value for fire_temp.temp_standard
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempStandard(String tempStandard) {
        this.tempStandard = tempStandard == null ? null : tempStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_voltage
     *
     * @return the value of fire_temp.temp_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempVoltage() {
        return tempVoltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_voltage
     *
     * @param tempVoltage the value for fire_temp.temp_voltage
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempVoltage(String tempVoltage) {
        this.tempVoltage = tempVoltage == null ? null : tempVoltage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_current
     *
     * @return the value of fire_temp.temp_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempCurrent() {
        return tempCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_current
     *
     * @param tempCurrent the value for fire_temp.temp_current
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempCurrent(String tempCurrent) {
        this.tempCurrent = tempCurrent == null ? null : tempCurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_texture
     *
     * @return the value of fire_temp.temp_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempTexture() {
        return tempTexture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_texture
     *
     * @param tempTexture the value for fire_temp.temp_texture
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempTexture(String tempTexture) {
        this.tempTexture = tempTexture == null ? null : tempTexture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_setting
     *
     * @return the value of fire_temp.temp_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempSetting() {
        return tempSetting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_setting
     *
     * @param tempSetting the value for fire_temp.temp_setting
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempSetting(String tempSetting) {
        this.tempSetting = tempSetting == null ? null : tempSetting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_size
     *
     * @return the value of fire_temp.temp_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempSize() {
        return tempSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_size
     *
     * @param tempSize the value for fire_temp.temp_size
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempSize(String tempSize) {
        this.tempSize = tempSize == null ? null : tempSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_des
     *
     * @return the value of fire_temp.temp_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempDes() {
        return tempDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_des
     *
     * @param tempDes the value for fire_temp.temp_des
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempDes(String tempDes) {
        this.tempDes = tempDes == null ? null : tempDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_push
     *
     * @return the value of fire_temp.temp_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public Integer getTempPush() {
        return tempPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_push
     *
     * @param tempPush the value for fire_temp.temp_push
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempPush(Integer tempPush) {
        this.tempPush = tempPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_linkman
     *
     * @return the value of fire_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempLinkman() {
        return tempLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_linkman
     *
     * @param tempLinkman the value for fire_temp.temp_linkman
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempLinkman(String tempLinkman) {
        this.tempLinkman = tempLinkman == null ? null : tempLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fire_temp.temp_phone
     *
     * @return the value of fire_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public String getTempPhone() {
        return tempPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fire_temp.temp_phone
     *
     * @param tempPhone the value for fire_temp.temp_phone
     *
     * @mbg.generated Fri Mar 20 13:13:37 GMT+08:00 2020
     */
    public void setTempPhone(String tempPhone) {
        this.tempPhone = tempPhone == null ? null : tempPhone.trim();
    }
}